bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: null
model_type: custom
python_version: py38
requirements:
- torch==1.12.1
- torchvision==0.13.1
- numpy==1.23.1
- albumentations==1.3.0
- opencv-python
- imageio==2.9.0
- imageio-ffmpeg==0.4.2
- pytorch-lightning==1.5.0
- omegaconf==2.1.1
- test-tube>=0.7.5
- einops==0.3.0
- transformers==4.19.2
- webdataset==0.2.5
- kornia==0.6
- open_clip_torch==2.0.2
- invisible-watermark>=0.1.5
- torchmetrics==0.6.0
- timm==0.6.12
- addict==2.4.0
- yapf==0.32.0
- prettytable==3.6.0
- safetensors==0.2.7
- truss
resources:
  cpu: "3"
  memory: 30Gi 
  use_gpu: false
secrets: {}
spec_version: '2.0'
system_packages:
- ffmpeg
